package migmigration

// Phase Descriptions
var PhaseDescriptions = map[string]string{
	"Started":                         "Migration started.",
	"Prepare":                         "Preparing for migration.",
	"EnsureCloudSecretPropagated":     "Ensuring Velero has latest Replication Repository storage credentials.",
	"PreBackupHooks":                  "Waiting for user-defined pre-backup hooks to complete.",
	"PostBackupHooks":                 "Waiting for user-defined post-backup hooks to complete.",
	"PreRestoreHooks":                 "Waiting for user-defined pre-restore hooks to complete.",
	"PostRestoreHooks":                "Waiting for user-defined post-restore hooks to complete.",
	"PreBackupHooksFailed":            "Migration failed while running user-defined pre-backup hooks.",
	"PostBackupHooksFailed":           "Migration failed while running user-defined post-backup hooks.",
	"PreRestoreHooksFailed":           "Migration failed while running user-defined pre-restore hooks.",
	"PostRestoreHooksFailed":          "Migration failed while running user-defined post-restore hooks.",
	"EnsureInitialBackup":             "Creating initial Velero backup.",
	"InitialBackupCreated":            "Waiting for initial Velero backup to complete.",
	"InitialBackupFailed":             "Migration failed during initial Velero backup.",
	"AnnotateResources":               "Adding migration annotations and labels to PVs, PVCs, Pods, ImageStreams, and Namespaces. Annotations and labels provide migration instructions to Velero, Velero Plugins and Restic.",
	"EnsureStagePodsFromRunning":      "Creating Stage Pods and mounting PVC data from running Pods.",
	"EnsureStagePodsFromTemplates":    "Creating Stage Pods and mounting PVC data from DeploymentTemplates, DeploymentConfigs, ReplicationControllers, DaemonSets, StatefulSets, ReplicaSets, CronJobs and Jobs.",
	"EnsureStagePodsFromOrphanedPVCs": "Creating Stage Pods and mounting PVC data from unmounted PVCs.",
	"StagePodsCreated":                "Waiting for all Stage Pods to start.",
	"StagePodsFailed":                 "Migration failed due to some Stage Pods failing to start.",
	"RestartRestic":                   "Restarting Restic Pods, ensuring latest PVC mounts are available for PVC backups.",
	"ResticRestarted":                 "Waiting for Restic Pods to restart, ensuring latest PVC mounts are available for PVC backups.",
	"QuiesceApplications":             "Quiescing (Scaling to 0 replicas): Deployments, DeploymentConfigs, StatefulSets, ReplicaSets, DaemonSets, CronJobs and Jobs.",
	"EnsureQuiesced":                  "Waiting for Quiesce (Scaling to 0 replicas) to finish for Deployments, DeploymentConfigs, StatefulSets, ReplicaSets, DaemonSets, CronJobs and Jobs.",
	"UnQuiesceApplications":           "UnQuiescing (Scaling to N replicas) Deployments, DeploymentConfigs, StatefulSets, ReplicaSets, DaemonSets, CronJobs and Jobs.",
	"EnsureStageBackup":               "Creating a stage backup.",
	"StageBackupCreated":              "Waiting for completion of stage backup.",
	"StageBackupFailed":               "Migration failed during stage backup.",
	"EnsureInitialBackupReplicated":   "Waiting for initial Velero backup replication to target cluster.",
	"EnsureStageBackupReplicated":     "Waiting for initial Velero backup replication to target cluster.",
	"EnsureStageRestore":              "Creating a stage Velero restore including OpenShift resources and PVCs.",
	"StageRestoreCreated":             "Waiting for completion of stage Velero restore.",
	"StageRestoreFailed":              "Migration failed during stage Velero restore.",
	"EnsureFinalRestore":              "Creating final Velero restore.",
	"FinalRestoreCreated":             "Waiting for completion of final Velero restore.",
	"FinalRestoreFailed":              "Migration failed during final Velero restore.",
	"Verification":                    "Verifying health of migrated Pods.",
	"EnsureStagePodsDeleted":          "Deleting any leftover stage Pods.",
	"EnsureStagePodsTerminated":       "Waiting for leftover stage Pod deletion to finish.",
	"EnsureAnnotationsDeleted":        "Removing migration annotations and labels from PVs, PVCs, Pods, ImageStreams, and Namespaces. Annotations and labels provide migration instructions to Velero, Velero Plugins and Restic.",
	"EnsureMigratedDeleted":           "Rolling back. Waiting for migrated resource deletion.",
	"DeleteMigrated":                  "Rolling back. Deleting migrated resources from target cluster.",
	"DeleteBackups":                   "Deleting Velero Backups created during migration.",
	"DeleteRestores":                  "Deleting Velero Restores created during migration.",
	"MigrationFailed":                 "Migration failed.",
	"Canceling":                       "Migration cancellation in progress.",
	"Canceled":                        "Migration canceled.",
	"Completed":                       "Migration completed.",
}
