package migmigration

// Phase Descriptions
var PhaseDescriptions = map[string]string{
	"Started":                         "Migration started.",
	"Prepare":                         "Preparing for migration.",
	"EnsureCloudSecretPropagated":     "Ensuring Velero has latest Replication Repository storage credentials",
	"PreBackupHooks":                  "Running user defined `PreBackupHooks` and waiting for completion.",
	"PostBackupHooks":                 "Running user defined `PreBackupHooks` and waiting for completion.",
	"PreRestoreHooks":                 "Running user defined `PreRestoreHooks` and waiting for completion.",
	"PostRestoreHooks":                "Running user defined `PostRestoreHooks` and waiting for completion.",
	"PreBackupHooksFailed":            "Migration failed while running user defined `PreBackupHooks`.",
	"PostBackupHooksFailed":           "Migration failed while running user defined `PostBackupHooks`.",
	"PreRestoreHooksFailed":           "Migration failed while running user defined `PreRestoreHooks`.",
	"PostRestoreHooksFailed":          "Migration failed while running user defined `PostRestoreHooks`.",
	"EnsureInitialBackup":             "Creating 'Initial' Velero Backup.",
	"InitialBackupCreated":            "Waiting for completion of 'Initial' Velero Backup.",
	"InitialBackupFailed":             "Migration failed during 'Initial' Velero Backup.",
	"AnnotateResources":               "Adding migration annotations and labels to PVs, PVCs, Pods, ImageStreams, and Namespaces. Annotations and labels provide migration instructions to Velero, Velero Plugins and Restic.",
	"EnsureStagePodsFromRunning":      "Creating Stage Pods mounting PVC data from running Pods.",
	"EnsureStagePodsFromTemplates":    "Creating Stage Pods mounting PVC data from DeploymentTemplates, DeploymentConfigs, ReplicationControllers, DaemonSets, StatefulSets, ReplicaSets, CronJobs and Jobs.",
	"EnsureStagePodsFromOrphanedPVCs": "Creating Stage Pods mounting PVC data from unmounted PVCs.",
	"StagePodsCreated":                "Waiting for all Stage Pods to start.",
	"StagePodsFailed":                 "Migration failed due to some Stage Pods failing to start.",
	"RestartRestic":                   "Restarting Restic Pods, ensuring latest PVC mounts are available for PVC backups.",
	"ResticRestarted":                 "Waiting for Restic Pods to restart, ensuring latest PVC mounts are available for PVC backups.",
	"QuiesceApplications":             "Quiescing (Scaling to 0 replicas): Deployments, DeploymentConfigs, StatefulSets, ReplicaSets, DaemonSets, CronJobs and Jobs.",
	"EnsureQuiesced":                  "Waiting for Quiesce (Scaling to 0 replicas) to finish for Deployments, DeploymentConfigs, StatefulSets, ReplicaSets, DaemonSets, CronJobs and Jobs.",
	"UnQuiesceApplications":           "UnQuiescing (Scaling to N replicas) Deployments, DeploymentConfigs, StatefulSets, ReplicaSets, DaemonSets, CronJobs and Jobs.",
	"EnsureStageBackup":               "Creating 'Stage' Backup.",
	"StageBackupCreated":              "Waiting for completion of 'Stage' Backup.",
	"StageBackupFailed":               "Migration failed during 'Stage' Backup.",
	"EnsureInitialBackupReplicated":   "Waiting for 'initial' Velero Backup replication to target cluster.",
	"EnsureStageBackupReplicated":     "Waiting for 'initial' Velero Backup replication to target cluster.",
	"EnsureStageRestore":              "Creating 'Stage' Velero Restore including OpenShift resources and PVCs.",
	"StageRestoreCreated":             "Waiting for completion of 'Stage' Velero Restore.",
	"StageRestoreFailed":              "Migration failed during 'Stage' Velero Restore.",
	"EnsureFinalRestore":              "Creating 'Final' Velero Restore.",
	"FinalRestoreCreated":             "Waiting for completion of 'Final' Velero Restore.",
	"FinalRestoreFailed":              "Migration failed during 'Final' Velero Restore.",
	"Verification":                    "Verifying health of migrated Pods.",
	"EnsureStagePodsDeleted":          "Deleting any leftover Stage Pods.",
	"EnsureStagePodsTerminated":       "Waiting for leftover Stage Pod deletion to finish.",
	"EnsureAnnotationsDeleted":        "Removing migration annotations and labels from PVs, PVCs, Pods, ImageStreams, and Namespaces. Annotations and labels provide migration instructions to Velero, Velero Plugins and Restic.",
	"EnsureMigratedDeleted":           "Rolling back. Waiting for migrated resource deletion.",
	"DeleteMigrated":                  "Rolling back. Deleting migrated resources from target cluster.",
	"DeleteBackups":                   "Deleting Velero Backups created during migration.",
	"DeleteRestores":                  "Deleting Velero Restores created during migration.",
	"MigrationFailed":                 "Migration failed.",
	"Canceling":                       "Migration cancellation in progress.",
	"Canceled":                        "Migration canceled.",
	"Completed":                       "Migration completed.",
}
